return {
  OnlyOwner = 'This method is only available to the Owner',
  MessageDataRequired = 'Message data is required to process request',
  NumberValueRequired = 'Number value required',
  IntegerValueRequired = 'Integer value required',
  FloatValueRequired = 'Floating point value required',
  BooleanValueRequired = 'Boolean value required',
  InvalidH3Cell = 'Invalid H3 Cell data',
  InvalidCertificate = 'Invalid certificate',
  FingerprintRequired = 'Fingerprint required',
  FingerprintsRequired = 'Fingerprints required',
  DuplicateFingerprint = 'Duplicate Fingerprint',
  UnknownFingerprint = 'Unknown Fingerprint',
  OperatorCertificatesRequired = 'Operator Certificates required',
  OnlyRelayOperatorCanRenounce = 'Only the Relay Operator can renounce',
  AddressIsBlocked = 'Address is blocked',
  AddressRequired = 'Address is required',
  InvalidAddress = 'Invalid Address',
  AddressIsNotBlocked = 'Address is not blocked',
  InvalidFingerprint = 'Invalid Fingerprint',
  RegistrationCreditAlreadyAdded = 'Registration Credit already added',
  RegistrationCreditRequired = 'Registration Credit required',
  RegistrationCreditDoesNotExist = 'Registration Credit does not exist',
  FamiliesRequiredAsMessageData = 'Families required as Message Data',
  InvalidFamilies = 'Invalid Families',
  FamilyNotSet = 'Family not set',
  AlreadyInitialized = 'Already Initialized',
  InvalidBlockedOperatorAddressesValue =
    'Invalid BlockedOperatorAddresses value',
  InvalidVerifiedHardwareValue = 'Invalid VerifiedHardware value',
  InvalidInitializedValue = 'Invalid _initialized value'
}
