# BUILD
FROM node:20.18-alpine AS build

RUN apk update && \
    apk add --no-cache jq && \
    rm -rf /var/cache/apk/*

WORKDIR /usr/src/app

COPY --chown=node:node ./ao .

RUN npm install

RUN npm run build

USER node

## TODO -> module build flow
# FROM p3rmaw3b/ao:0.1.5 AS ao-build
# WORKDIR /usr/src/app
# COPY --from=build /usr/src/app/dist .
