export const FINGERPRINT_REQUIRED = 'Fingerprint required'
export const INVALID_FINGERPRINT = 'Invalid fingerprint'
export const ADDRESS_REQUIRED = 'Address required'
export const INVALID_ADDRESS = 'Invalid address'
export const PUBLIC_KEY_REQUIRED = 'Public Key is required and must valid'
export const ENABLED_REQUIRED = 'Enabled must be a boolean'
export const FINGERPRINTS_MUST_BE_ARRAY = 'Valid array of fingerprints required'
